# Generated by Django 5.0.6 on 2024-06-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('ruolo', models.SmallIntegerField(choices=[(0, 'Responsabile'), (1, 'Operatore'), (2, 'Superutente')])),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=40)),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figli', to='api.nodo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodi', to='api.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Risorsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabile', models.BooleanField(default=False)),
                ('operatore', models.BooleanField(default=False)),
                ('titolo', models.CharField(max_length=40)),
                ('contenuto', models.TextField()),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risorse', to='api.nodo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risorse', to='api.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='api.risorsa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='api.utente')),
            ],
        ),
    ]
