# Generated by Django 5.0.6 on 2024-06-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('ruolo', models.SmallIntegerField(choices=[(0, 'Responsabile'), (1, 'Operatore'), (2, 'Superutente')])),
            ],
        ),
    ]
