# Generated by Django 5.0.6 on 2024-06-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0004_alter_utente_managers_utente_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='ruolo',
            field=models.SmallIntegerField(choices=[(0, 'Responsabile'), (1, 'Operatore'), (2, 'Superutente')]),
        ),
    ]
