# Generated by Django 5.0.6 on 2024-06-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0006_alter_utente_options_utente_date_joined_utente_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utente',
            options={},
        ),
        migrations.RemoveField(
            model_name='utente',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='last_name',
        ),
    ]
