# Generated by Django 5.0.6 on 2024-06-19 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=40)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodi', to='utente.utente')),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figli', to='nodo.nodo')),
            ],
        ),
    ]
