# Generated by Django 5.0.6 on 2024-06-19 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risorsa', '0001_initial'),
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='utente.utente')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='risorsa.risorsa')),
            ],
        ),
    ]
