# Generated by Django 5.0.6 on 2024-06-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commento',
            name='contenuto',
            field=models.TextField(default=None),
        ),
    ]
