# Generated by Django 5.0.6 on 2024-06-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risorsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risorsa',
            name='contenuto',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='risorsa',
            name='titolo',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
